services:
  api:
    container_name: base-api
    build:
      context: .
      dockerfile: docker/api/Dockerfile
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
        USERNAME: dev
    volumes:
      - ./api:/var/www
    working_dir: /var/www
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  spa:
    container_name: base-spa
    build:
      context: .
      dockerfile: docker/spa/Dockerfile
    volumes:
      - ./spa:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - 5173:5173
    depends_on:
      - api

  db:
    image: mysql:8.4
    container_name: base-db
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: base
      MYSQL_PASSWORD: base_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis
    container_name: base-redis
    restart: on-failure
    ports:
      - 6379:6379
  
volumes:
  db_data:

